### ISSUE TITLE
Questions about `src/pages/index.tsx`...

### ISSUE THREAD

**Issue by soykje** [BiscuiTech/BiscuiT#110]
Hello! :wave:

I recently built my own website, also using NextJS and with inspiration from your great work on [mulitlingual support for SSG projects](https://dev.to/biscuitech/i18n-with-next-js-and-full-ssg-support-2aih)! :clap:

There were two points that I would be happy to discuss with you, if that's ok....

#### 1.
On your `src/pages/index.tsx`, why using `window.location.replace` instead of next router? If I'm right, you could have achieve the same goal with `router.replace('/[lang]', `/${getInitialLocale()}`)`, couldn't you? So if true is there a particular reason on using the `window.location.replace` here?

#### 2.
Finally, I was having some SEO _issues_, as the root path without language was not properly crawled by Twitter Card Validator:
- https://soykje.gitlab.io/(fr|en) => :+1: 
- https://soykje.gitlab.io/ => :-1: 

And I was thinking about what solution I could find:
- rewriting `/` to `/fr` (default locale), but I was not sure about the risk of duplicate content for robots... :thinking: 
- copying code from default locale homepage to index...Hmm seems dirty to me :thinking: 
- using the same approach as the MDN website, which seems to apply quite well with yours (and mine, so^^). Then I'd have to copy my SEO meta tags to this `src/pages/index.tsx` in order to make Twitter Card Valdator happy (and other SEO tools, I guess...).

I chose this last option, and added my SEO tags (component) in this page. And now here is my _new_ `src/pages/index.js`:
```javascript
import PropTypes from 'prop-types'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'

import { getI18n } from '@utils/api'
import { DEFAULT_LOCALE, useLocale } from '@utils/locale'

import Seo from '@components/Seo'

import { getInitialLocale } from '@utils/locale'

export default function Index({ translations }) {
  const { t } = useLocale(translations)
  const router = useRouter()

  useEffect(() => {
    router.replace('/[lang]', `/${getInitialLocale()}`)
  })

  return (
    <>
      <Seo description={[t('description.title'), t('description.subtitle')].join(' ')} />

      <Head>
        <meta key="robots" name="robots" content="noindex, nofollow" />
      </Head>
    </>
  )
}

Index.propTypes = {
  translations: PropTypes.arrayOf(
    PropTypes.object
  ).isRequired
}

export async function getStaticProps({ params }) {
  const lang = params?.lang || DEFAULT_LOCALE

  const translations = getI18n(lang, 'home')

  return { props: { translations }}
}
```

What do you think about it? I'd be very happy to discuss about these points with you! Don"t hesitate also to take a look at [my repo](https://gitlab.com/soykje/soykje.gitlab.io) :wink:

**Comment by BiscuiTech** [comment]
Hey! Thanks for the kind words. Don't forget to also thank the original creator https://github.com/fwojciec ;)

As for number 1:
There's no inherent reasons why I chose `window.replace ` over `router.replace`. You could very well go with the nextjs method.

2: 
You could add a simple logic of rel=canonical to avoid duplicate content penalties, but that wouldn't fix the Twitter crawler issue. I quite like your take actually and might actually try to fix my SEO issues with your code :)

As a side note, nextjs itself has opened a RFC to have **native** i18n functions. This is quite exciting and would invite you to voice your comments over at https://github.com/vercel/next.js/discussions/17078

**Comment by soykje** [comment]
Thank you for your answer! I'm actually working on an incoming blog post about multilingual support on NextJS SSG, with a large credit to your work and to the one from @fwojciec of course! :slightly_smiling_face: 
 I'll be happy to exchange with you about our respective i18n projects, as they are pretty close... And glad if some of my lines can help you in some way!
I discovered recently the NextJS discussions, and saw indeed there was an RFC about this i18n topic... Didn't take much time to get really involved there, but I guess it is just a matter of time! :slightly_smiling_face:
